### ISSUE TITLE
 Cannot start ceramic node in local mode following "Getting started"

### ISSUE THREAD

**Issue by christiaanpauw** [ceramicstudio/js-composedb#111]
# Description
I am on OS X 11.6.8, with Node v18.15.0

After completing the installation of Ceramic, ComposeDB and via npm 

I ran:
`npx @ceramicnetwork/cli daemon `
as instructed [here](https://composedb.js.org/docs/0.4.x/set-up-your-environment#run-a-ceramic-node)

Instead of the expected 

`IMPORTANT: Ceramic API running on 0.0.0.0:7007`

I got:
```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by JulissaDantes** [comment]
Hey Cristian, I understand this issue was created a while ago but hopefully you were able to run the Ceramic node. But that output is just a warning by [node](https://nodejs.org/en/learn/getting-started/introduction-to-nodejs), it shouldnt stop you from running a Ceramic node. You should be able to see this message display after that warning.
